spring.application.name=CarePlus01
# 1. Configuration H2 (Base de données en mémoire)
spring.datasource.url=jdbc:h2:mem:careplusdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Activer la console Web (pour que tu puisses voir la BDD dans ton navigateur)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. JPA / Hibernate (Création automatique des tables)
# 'update' met à jour le schéma si tu changes ton code Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
